server:
  port: 20002
spring:
  cloud:
    consul:
      host: localhost
      #  Consul监听端口8500
      port: 8500
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置服务健康检测地址  供Consul 调用
#        health-check-path: /health
        # consul 健康检测频率
#        health-check-interval: 15s
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}
  application:
    name: service-email
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 短信配置
  mail:
    host: smtp.126.com
    protocol: smtp
    username: houshuai0816@126.com
    password: houshuai
    default-encoding: utf-8
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
email:
  active-time: 6000
