server:
  port: 20003
spring:
  cloud:
    consul:
      host: localhost
      #  Consul监听端口8500
      port: 8500
      enabled: true
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置服务健康检测地址  供Consul 调用
        health-check-path: /api/health
        # consul 健康检测频率
        health-check-interval: 15s
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}:${server.port}
        enabled: true
        service-name: ${spring.application.name}
  application:
    name: service-email
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.95.207.79:3306/account?useSSL=false
      username: root
      password: root
      dbcp2:
        # 初始化连接数
        initial-size: 5
        # 最小连接数
        min-idle: 5
        # 最大连接数
        max-idle: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 短信配置
  mail:
    host: smtp.126.com
    protocol: smtp
    username: houshuai0816@126.com
    password: houshuai0816
    default-encoding: utf-8
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
email:
  activeTime: 6000
  defaultSender: houshuai0816@126.com
