server:
  port: 10100
spring:
  cloud:
    consul:
      host: 47.95.207.79
      #  Consul监听端口8500
      port: 8500
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置服务健康检测地址  供Consul 调用
#        health-check-path: /health
        # consul 健康检测频率
#        health-check-interval: 15s
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}
  application:
    name: server-login
security:
  oauth2:
    resource:
      user-info-uri: http://loaclhost:10000/auth/user
      prefer-token-info: false
      service-id: ecology-oauth2


