spring:
#  elasticsearch:
#    jest:
#      uris: http://localhost:9200
#      username:
#      password:
#      read-timeout: 20000ms
#      connection-timeout: 20000ms
  data:
    elasticsearch:
      cluster-name: elasticsearh
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true

