server:
  port: 10002
spring:
  application:
    name: ecology-config
  cloud:
    config:
      server:
        git:
          uri: https://git.coding.net/houshuai0816/AndyProject.git
          search-paths: /config
      label: master
      password: hou.490130210
      username: houshuai0816@126.com
    consul:
      host: localhost
      #  Consul监听端口8500
      port: 8500
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置服务健康检测地址  供Consul 调用
        health-check-path: /api/health
        # consul 健康检测频率
        health-check-interval: 15s
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}:${server.port}
        enabled: true
        service-name: ${spring.application.name}