server:
  port: 10002
spring:
  application:
    name: ecology-config
  cloud:
    config:
      server:
        git:
          uri: https://git.coding.net/houshuai0816/AndyProject.git
          search-paths: /config
      label: master
      password: hou.490130210
      username: houshuai0816@126.com