server:
  port: 10000
spring:
  cloud:
    consul:
      host: localhost
      #  Consul监听端口8500
      port: 8500
      discovery:
        # 配置服务注册到Consul上
        register: true
        # 配置服务健康检测地址  供Consul 调用
        health-check-path: /api/health
        # consul 健康检测频率
        health-check-interval: 15s
        # 配置注册到consul 服务的id
        instance-id: ${spring.application.name}:${server.port}
        enabled: true
        service-name: ${spring.application.name}
      enabled: true
  application:
    name: ecology-getway
  thymeleaf:
    cache: true
zuul:
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000
  routes:
    ratelimit-api:
      path: /ratelimit-api/**
      service-id: service-client
#      sensitiveHeaders: "*"
    auth:
      path: /auth/**
#      sensitiveHeaders: "*"
      service-id: ecology-oauth2
    user-center:
      path: /test/**
#      sensitiveHeaders: "*"
      service-id: service-account-center
  ratelimit:
    key-prefix: ratelimit-api
#     启动限流服务
    enabled: true
    behind-proxy: true
    default-policy:
#       请求数量
      limit: 100
#       请求总时间
      quota: 20
#       统计窗口刷新时间
      refresh-interval: 60
#       限流类型
      type: url
  add-proxy-headers: true
  add-host-header: true
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:${server.port}/auth/oauth/token
#      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
#      client-id: open-api
#    resource:
#      user-info-uri: http://localhost:${server.port}/auth/user
#      prefer-token-info: false
